name: Doker Build and Deploy to AWS ECR
on:
  push:
    [branches: [main, deploy]]
  pull_request:
    [branches: [main]]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production # Este trabajo se ejecutará en el entorno de producción
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Si usas credenciales temporales
          aws-region: us-east-1
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
      
      - name: Build image
        run: |
          docker build -t innovad/Frontend:latest .

      - name: Tag image
        run: |
          docker tag innovad/Frontend:latest <secrets.AWS_ACCOUNT_ID>.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/innovad/Frontend:latest
      
      - name: Push image to ECR
        run: |
          docker push <secrets.AWS_ACCOUNT_ID>.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/innovad/Frontend:latest