name: docker-compose.yml
version: '3.8'
services:
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: innovadb
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./front_despacho
    ports:
      - "3000:3000"
    depends_on:
      - backend-despachos
      - backend-ventas
  
  backend-despachos:
    build: ./back-Despachos_SpringBoot
    ports:
      - "8080:8080"
    depends_on:
      - database
  
  backend-ventas:
    build: ./back-Ventas_SpringBoot
    ports:
      - "8081:8080"
    depends_on:
      - database

volumes:
  db_data: 