name: Docker Build and Deploy to AWS ECR
on:
  push:
    branches: [ main, deploy ]# Trigger de despliegue en ramas main y deploy
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Verificación de carpetas (Para diagnosticar si falla)
          ls -R
          
          # Frontend
          docker build -t $ECR_REGISTRY/innovad/frontend:latest ./front_despacho
          docker push $ECR_REGISTRY/innovad/frontend:latest
          
          # Backend Despachos
          docker build -t $ECR_REGISTRY/innovad/backend-despachos:latest ./back-Despachos_SpringBoot
          docker push $ECR_REGISTRY/innovad/backend-despachos:latest
          
          # Backend Ventas
          docker build -t $ECR_REGISTRY/innovad/backend-ventas:latest ./back-Ventas_SpringBoot
          docker push $ECR_REGISTRY/innovad/backend-ventas:latest